### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by danny-may** [blargbot/blargbot#107]
There are various missing method definitons in the bot that are causing some errors.
If they are here it is because I cannot fix them (Image commands) or I dont understand what they are meant to do.

- /src/dcommands/cah.js
  - `doit(msg, words)` missing
- /src/dcommands/catbot.js
  - `genlogs(msg, markov.userid, markov.id)` missing

**Comment by HunteRoi** [comment]
[To close] @danny-may
