### ISSUE TITLE
Custom randchoose command help?

### ISSUE THREAD

**Issue by miisukomm** [blargbot/blargbot#127]
Is there a way to make a custom command with the randchoose tag where you can specify the number of items you want to be generated? As well as making the generated items not repeat themselves? 

Not exactly a bug, but I believe I've seen another Discord server achieve the latter (I could be wrong), but I can't figure this out at all.

**Comment by Ratismal** [comment]
Could you give an example on the input/output that you would like for the custom command? I'm a bit confused about what you want.

For blargbot support and help with the BBTag language, I'd recommend going to our [support guild](https://support.blargbot.xyz), as there are many people there who would be happy to help you out in real-time.

Let me know if you need any more help. Thanks!

**Comment by HunteRoi** [comment]
[To close] @Ratismal
