### ISSUE TITLE
Unnecessary backticks/Strange design

### ISSUE THREAD

**Issue by ghost** [blargbot/blargbot#147]
https://github.com/blargbot/blargbot/blob/fc75ceba650f65188f8da3e74b30d0581b231c2e/src/dcommands/autoresponse.js#L124

This snippet has unnecessary backticks resulting in the following output:

![image](https://totally-not.a-sketchy.site/fa24be.png)

As you can see, the output shows **\`_autoresponse_X\`** instead of **_autoresponse_X** therefore causing a possible confusion. While it might be less "clean" (three colors instead of two), I suggest removing them. 

![image2](https://get.banned.today/886ccc.png)

**Comment by HunteRoi** [comment]
Agree 👍

**Comment by HunteRoi** [comment]
[To be closed] @Ratismal
