### ISSUE TITLE
Regexreplace | Max args length 

### ISSUE THREAD

**Issue by ghost** [blargbot/blargbot#163]
See here: 
https://github.com/blargbot/blargbot/blob/70229bfe1046bcf6a2b636677490342beab73102/src/tags/regexreplace.js#L38

Is there any particular reason why this is here? Or perhaps why it's undocumented in the help?

**Comment by Titansmasher** [comment]
There were performance concerns with longer regexes & applying complex regexes to long strings. 50,000 characters seemed like a reasonable limitation

**Comment by simoniz0r** [comment]
50k characters seems... a bit low IMO.  I'm no javascript expert, but I see no performance impact in the languages I use for over 200k characters.  The site that I was trying to parse here contains about 110k characters, and I download and run a regex expression on it in less than half a second. ( http://man.he.net/?topic=gpg&section=all ).

Also, I tried detecting when regexreplace outputs that too many arguments were passed, but I could not do this.  My tag just outputs nothing regardless of me trying to detect that the regexreplace failed.

**Comment by simoniz0r** [comment]
```
{set;~raw;{request;http://man.he.net/?topic={uriencode;{flag;_}}&section=all}}
{set;~request;{regexreplace;{regexreplace;{jget;{get;~raw};body};/<.*>/g;};/^\s*\n/gm;}}
{if;{get;~request};includes;Argument length exceeded limit;
{embed;{embedbuild;
title:man for {args;0};
url:http://manpages.ubuntu.com/manpages/bionic/{uriencode;{flag;_}};
thumbnail.url:https://cdn.discordapp.com/emojis/478073442311077889.gif?v=1&size=40;color:2C8EBE;}}{return}}
```

Is there some other method I should be using to detect when regexreplace fails?

**Comment by AlexTMjugador** [comment]
My two cents here: given that the maximum regexp length is 2000 characters, as `bu.createRegExp` will refuse to compile regexes when more characters are used by throwing an error, and that you can process up to 50,000 characters with a regexp that's in the limit (or even unsafe, if the library didn't classify it properly), I think it's reasonable to impose relatively low limits to minimize the possibility of performance problems.

Differently from your PC, you don't want someone you happen to share Blargbot server with hogging all the resources, do you? I think scalability and soft real time performance requirements are important for this project.

Addressing your use case, have you tried dividing the potentially long input string in smaller ones with `{substring}`?

**Comment by simoniz0r** [comment]
Either way, the fact that I haven't been able to detect when regexreplace fails is a problem.  I can't address this if I can't detect when regexreplace has failed.

**Comment by HunteRoi** [comment]
[To close] @Ratismal
