### ISSUE TITLE
Mute is easy to bypass

### ISSUE THREAD

**Issue by Cubixmeister** [blargbot/blargbot#182]
Users can easily bypass muted role by quitting and rejoining given discord guild.
Role is not reassigned after join on the same account in short time window.

**Comment by HunteRoi** [comment]
Hey there! Sorry for the late reply.

This is already possible using a custom mute command written with [BBTag](https://blargbot.xyz/tags) and the [greet](https://blargbot.xyz/commands#greet) built-in command.
While I understand your concern for this to be built natively, I think you would have a more efficient system if this was directly a per server thing implemented by yourself.

If you need help creating this, then feel free to head over to our [support server](https://discord.gg/015GVxZxI8rtlJgXF)! We'd be happy to help you :)

**Comment by AadityaRanka** [comment]
Some sort of hacks, no?
