### ISSUE TITLE
Suggestion - Self assigning a role through reacting to emoji - Reaction Role Menu

### ISSUE THREAD

**Issue by BoQsc** [blargbot/blargbot#184]
![An example](https://user-images.githubusercontent.com/21064622/69453936-af305c80-0d6d-11ea-81c7-651a396c7e01.png)

Blargbot needs a well known feature of Reaction Role Menu.

YAGPDB bot is a backbone of most servers for this kind of job and I would like to replace it with blargbot. This is probably not easy to implement, however haven't seen a suggestion about it, so I decided that it would be good to introduce this problem here.
https://www.youtube.com/watch?v=ENOttyXKDo8

**Comment by danny-may** [comment]
This is actually already possible using the BBTag system using the [`{waitreact}`](https://blargbot.xyz/tags#waitreaction) and [`{addrole}`](https://blargbot.xyz/tags#addrole) subtags. While it could be added natively, I think that something like this would be better suited as a per server thing implemented using bbtag. 

If you need help creating this, then feel free to head over to our [support server](https://discord.gg/015GVxZxI8rtlJgXF)

**Comment by HunteRoi** [comment]
If nobody wants to add something about this issue,, I am going to mark it as `[to close]` for @Ratismal.
