### ISSUE TITLE
waitreact and waitmessage condition not defaulting to true

### ISSUE THREAD

**Issue by HunteRoi** [blargbot/blargbot#199]
As stated by **RagingLink#9469** via the bug-report system, the following subtags have an optional parameter `condition` which should default to true if it isn't provided :
- `{waitmessage;[channels];[users];[condition];[timeout]}`
- `{waitreaction;<messages>;[users];[reactions];[condition];[timeout]}`

Subtags return `Condition must return 'true' or 'false'` with use case where it actually is an empty string and so shouldn't be interpreted as provided value : `{waitmessage;{channelid};{userid};;60}`.

Feedback available [here](https://blargbot.xyz/feedback/rec5myzRJj8Did5sx)

**Comment by HunteRoi** [comment]
I couldn't determine the way to solve this, so I decided to close the linked pull request as it was not bringing anything to patch the issue.

**Comment by RagingLink** [comment]
I'm like a month late. But the `[condition]` parameter is basically an empty BBtag Instance (no content) right ? So changing the condition inside the `if` to: 
```if (args[2] && args[2].content != '') {```
should work right? Since .content will be an empty string if it's ommited.
