### ISSUE TITLE
Modlog only logs bans, not kicks.

### ISSUE THREAD

**Issue by PeacefullNoob** [blargbot/blargbot#200]
Each time I kick a user, it doesn't get logged. I have set up a modlog channel and it works for bans, but not when i kick a user.

**Comment by HunteRoi** [comment]
Good evening @PeacefullNoob !

Thanks for your feedback. Do you use the `kick` built-in command in order to ban someone?
As [stated in the documentation](https://blargbot.xyz/commands#modlog), you don't need to use `ban` for it to get logged. However, it is not the case with the kick feature.

**Comment by PeacefullNoob** [comment]
I used the command **b!kick** to kick the user and it did not logged.

**Comment by HunteRoi** [comment]
Alright, I could reproduce the issue on the Support server. I'll take a look into it and see if I can get a pull request done before the end of the week. 
However, there are a few fixes and features awaiting for approval and merge. Don't expect the patch to release really soon as the priority is still set on debugging and fixing memory leaks.

Sorry for the inconvenience!

If you want to follow up on this issue, please join the [Discord Support server](https://discord.gg/Uv74eSD).

**Comment by PeacefullNoob** [comment]
No problem! Just wanted to tell you so it can get fixed. Thanks.

**Comment by HunteRoi** [comment]
The problem should be fixed in commit [cc90d99](https://github.com/blargbot/blargbot/commit/cc90d99acd86880d9bab90a08374ea9722aeb326). Thanks for reporting!
