### ISSUE TITLE
Where config.json

### ISSUE THREAD

**Issue by DibalaP** [blargbot/blargbot#286]

**Comment by danny-may** [comment]
There are some required configuration files that arent checked in. You can attempt to reverse engineer the config if you want, but self hosting the bot isnt something we support im afraid.

From the website [home page](https://blargbot.xyz/)
> Open-source does not mean portable. blargbot was not built with portability in mind, and is highly dependant on configs, files, and data structures that aren't available on github. It is open-source for allow people to look at its internals and learn how it works; for educational purposes. Hosting it yourself is not supported.
>
> If you're planning on reverse-engineering the bot to host it yourself, I can't say that I'll approve, but I won't stop you either. My requirements for this include giving me the heads-up and crediting me as the original author. See the license for more details.
