### ISSUE TITLE
[BUG] Weird behaviour on long censorlist

### ISSUE THREAD

**Issue by WolfenCLI** [blargbot/blargbot#289]
How to reproduce:

- Have more than 77 censors (tested with 154)
- run `b!censor info`

What is expected to happen:
- The bot gives the list of existing censors

What happened instead:
- The bot posted:
```
Oops! I tried to send a message that was too long. If you think this is a bug, please report it!

To see what I would have said, please visit [link to output]
```

- The output in the output link is truncated at 77 and then starts repeating:
```
...and 77 more.
...and 76 more.
...and 75 more.
...and 74 more.
...and 73 more.
...and 72 more.
...and 71 more.
...and 70 more.
...and 69 more.
...and 68 more.
...and 67 more.
...and 66 more.
...and 65 more.
...and 64 more.
...and 63 more.
```

**Comment by danny-may** [comment]
This should be fixed now, can you confirm @WolfenCLI ?

**Comment by WolfenCLI** [comment]
Yea it's fixed
