### ISSUE TITLE
Suggestion - Ability to only kick/ban at kickat/banat thresholds, not beyond.

### ISSUE THREAD

**Issue by Caketaco** [blargbot/blargbot#300]
Currently, the kickat and banat thresholds still kick/ban users after being warned past their values.

I would like to be able to change this so kicks/bans are only given _AT_ their given kickat/banat values, not beyond them.

For example, I would like to be able to do this:
If I had 'kickat' set to 3, and 'banat' set to 6, a user with 4 warns wouldn't be kicked again after being warned.
Only when they reach 3 warnings are they kicked, and 6 warnings are they banned.
Nothing else in between.

Could be changed with another server setting, 'actionpast' or something like that.

**Comment by HunteRoi** [comment]
Hey there! Thank you for the time you took to suggest your idea. I understand this might be tricky on your side to handle such cases.

As such, I think it is a good idea to be able to customize this behavior. For backward compatibility, the default action has to be the current one. It would still be a good idea to have a new setting that would allow to manage this.

We will look into that!
