### ISSUE TITLE
Can you pull up deleted log files?

### ISSUE THREAD

**Issue by Altilla** [blargbot/blargbot#32]
We're having an internal issue and some messages were deleted is there anyway to recover those deleted messages from your log files?

**Comment by Ratismal** [comment]
It's impossible to make deleted messages show up again, but you'd be able to retrieve the logs provided that
1. blargbot was in your guild at the time of the messages
2. You have the `makelogs` setting enabled (do `b!settings makelogs true`).
3. The messages are newer than one week old.

If the second isn't enabled, no chat logs would have ever been stored. I also do daily purges of week-old chatlogs.

Please let me know if this helps you.
