### ISSUE TITLE
Suggestion - b!docs UX improvements

### ISSUE THREAD

**Issue by mount2010** [blargbot/blargbot#336]
I have a few suggestions regarding the UX of b!docs.

- Under b!docs, add buttons or a select menu allowing the user to switch to, e.g. b!docs subtags instantly without having to run the command again.
- Allow users to continue switching between categories after they've selected one. Currently, to switch to another category, you have to run b!docs again, which is inconvenient, especially when you're working on something.
- To add to that, perhaps save the previous category selected and display that when b!docs subtags is run again.
- Add a search function. Possible implementation would be a button that pops up a modal which prompts the user for a search term when clicked. This will help users search through the categories for a subtag that they need.
- Perhaps allow multiple selections within the selector (which Discord supports) to view multiple categories at once, which would be extremely useful when working on a large project. This could perhaps be saved and shown again when b!docs subtags is run again.

**Comment by danny-may** [comment]
> Under b!docs, add buttons or a select menu allowing the user to switch to, e.g. b!docs subtags instantly without having to run the command again.

> Allow users to continue switching between categories after they've selected one. Currently, to switch to another category, you have to run b!docs again, which is inconvenient, especially when you're working on something.

> Add a search function. Possible implementation would be a button that pops up a modal which prompts the user for a search term when clicked. This will help users search through the categories for a subtag that they need.

> Perhaps allow multiple selections within the selector (which Discord supports) to view multiple categories at once, which would be extremely useful when working on a large project. This could perhaps be saved and shown again when b!docs subtags is run again.

100% agree, and I want to get the help command to function similarly. The reason I didnt do it for the initial release was because I dont want these menu constructs to timeout, id need to have some way to persist them between restarts too.

> To add to that, perhaps save the previous category selected and display that when b!docs subtags is run again.

Im not completely sure with this, I dont think we want to start making help commands stateful, but maybe @Ratismal has a different view on that.

**Comment by danny-may** [comment]
In general, I dont want "orphaned" controls, buttons or selects that blarg wont respond to. With that, we need stuff to either time out & be removed, or function across restarts. It shouldnt be difficult to make it persist, either fit all the needed info into the `customid` of the control, or add a db table to store it.
