### ISSUE TITLE
"your guild is not correctly configured yet"

### ISSUE THREAD

**Issue by DianaCorsten** [blargbot/blargbot#368]
![image](https://user-images.githubusercontent.com/109924302/180866666-3e35d425-218b-4a05-80e1-027e552be29c.png)

commands that apply persistent changes to the server, like "prefix" do not work, and attempting to invoke "settings" produces the error message "your guild is not correctly configured yet, try again later", which has been happening for several days.

**Comment by danny-may** [comment]
There is a PR already open that will hopefully fix this. For now try using the `b!bot reset` command

**Comment by DianaCorsten** [comment]
> There is a PR already open that will hopefully fix this (#366). For now try using the `b!bot reset` command

thank you, that worked
